/*
 * Copyright (c) 2026 Ali Rashid.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package zio.jwt.crypto

import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate

import zio.jwt.Base64UrlString

class X509ExtensionsSuite extends munit.FunSuite:

  /** Loads test-cert.der from classpath resources (generated by keytool). */
  private lazy val cert: X509Certificate =
    import scala.language.unsafeNulls
    val is = getClass.getResourceAsStream("/test-cert.der")
    assert(is != null, "test-cert.der not found on classpath — run: keytool -genkeypair ... (see README)")
    try
      val cf = CertificateFactory.getInstance("X.509")
      cf.generateCertificate(is).asInstanceOf[X509Certificate]
    finally is.close() // scalafix:ok

  test("x5t returns non-empty Base64UrlString") {
    val thumbprint = cert.x5t
    val str = Base64UrlString.unwrap(thumbprint)
    assert(str.nonEmpty, "x5t thumbprint should not be empty")
    // SHA-1 produces 20 bytes → 27 base64url chars (no padding)
    assertEquals(str.length, 27)
  }

  test("x5tS256 returns non-empty Base64UrlString") {
    val thumbprint = cert.x5tS256
    val str = Base64UrlString.unwrap(thumbprint)
    assert(str.nonEmpty, "x5tS256 thumbprint should not be empty")
    // SHA-256 produces 32 bytes → 43 base64url chars (no padding)
    assertEquals(str.length, 43)
  }

  test("x5t is deterministic") {
    assertEquals(cert.x5t, cert.x5t)
  }

  test("x5tS256 is deterministic") {
    assertEquals(cert.x5tS256, cert.x5tS256)
  }

  test("x5t and x5tS256 produce different values") {
    assertNotEquals(cert.x5t, cert.x5tS256)
  }

  test("x5t contains only base64url characters") {
    val str = Base64UrlString.unwrap(cert.x5t)
    assert(str.forall(c => c.isLetterOrDigit || c == '-' || c == '_'), s"x5t contains non-base64url characters: $str")
  }

  test("x5tS256 contains only base64url characters") {
    val str = Base64UrlString.unwrap(cert.x5tS256)
    assert(str.forall(c => c.isLetterOrDigit || c == '-' || c == '_'), s"x5tS256 contains non-base64url characters: $str")
  }

end X509ExtensionsSuite
